### ISSUE TITLE
部分Python版本下uiautomation依赖库问题导致import时报错

### ISSUE THREAD

**Issue by 476491966** [GuanYixuan/pyJianYingDraft#12]

**Comment by GuanYixuan** [comment]
这边本地测试是在Win 10上做的，用了Python `3.8.10` 和 `3.11.9`两个版本，似乎都没发现问题

可以放一下具体代码和报错信息，这样比较容易查找问题

**Comment by 476491966** [comment]
已解决，感谢！部分python版本确实会有依赖不兼容的问题

**Comment by GuanYixuan** [comment]
具体有哪些Python版本会出现依赖不兼容的情况？我可以在readme里加一句提示

**Comment by 476491966** [comment]
我在使用3.13，3.7.7，3.9是不可以的，最后也是3.8.9才可以

**Comment by GuanYixuan** [comment]
那么这些版本具体会报什么错呢？是跟`pymediainfo`相关的还是和`uiautomation`相关的

**Comment by zzZ-F** [comment]
我有过类似情况，当时我装的python 3.13 
运行了 python .\generate_draft.py之后然后显示
Traceback (most recent call last):
  File "D:\script\longEnglish\pyJianYingDraft\generate_draft.py", line 5, in <module>
    import pyJianYingDraft as draft  # 这里导入整个包并重命名为 draft
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\script\longEnglish\pyJianYingDraft\pyJianYingDraft\__init__.py", line 20, in <module>
    from .jianying_controller import Jianying_controller
  File "D:\script\longEnglish\pyJianYingDraft\pyJianYingDraft\jianying_controller.py", line 5, in <module>
    import uiautomation as uia
  File "D:\script\longEnglish\pyJianYingDraft\venv\Lib\site-packages\uiautomation\__init__.py", line 4, in <module>
    from .uiautomation import *
  File "D:\script\longEnglish\pyJianYingDraft\venv\Lib\site-packages\uiautomation\uiautomation.py", line 24, in <module>
    import comtypes  # need 'pip install comtypes'
    ^^^^^^^^^^^^^^^
  File "D:\script\longEnglish\pyJianYingDraft\venv\Lib\site-packages\comtypes\__init__.py", line 177, in <module>
    from comtypes._post_coinit import _shutdown
  File "D:\script\longEnglish\pyJianYingDraft\venv\Lib\site-packages\comtypes\_post_coinit\__init__.py", line 15, in <module>
    from comtypes._post_coinit.unknwn import _shutdown  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\script\longEnglish\pyJianYingDraft\venv\Lib\site-packages\comtypes\_post_coinit\unknwn.py", line 371, in <module>
    class _compointer_base(c_void_p, metaclass=_compointer_meta):
    ...<89 lines>...
            return value.QueryInterface(cls.__com_interface__)
  File "D:\script\longEnglish\pyJianYingDraft\venv\Lib\site-packages\comtypes\_post_coinit\unknwn.py", line 93, in __new__
    p = type(_compointer_base)(
             ^^^^^^^^^^^^^^^^
NameError: name '_compointer_base' is not defined. Did you mean: '_compointer_meta'?

然后安装了pip install comtypes==1.1.9 这个版本

后面又报错
Traceback (most recent call last):
  File "D:\script\longEnglish\pyJianYingDraft\generate_draft.py", line 5, in <module>
    import pyJianYingDraft as draft  # 这里导入整个包并重命名为 draft
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\script\longEnglish\pyJianYingDraft\pyJianYingDraft\__init__.py", line 20, in <module>
    from .jianying_controller import Jianying_controller
  File "D:\script\longEnglish\pyJianYingDraft\pyJianYingDraft\jianying_controller.py", line 5, in <module>
    import uiautomation as uia
  File "D:\script\longEnglish\pyJianYingDraft\venv\Lib\site-packages\uiautomation\__init__.py", line 4, in <module>
    from .uiautomation import *
  File "D:\script\longEnglish\pyJianYingDraft\venv\Lib\site-packages\uiautomation\uiautomation.py", line 24, in <module>
    import comtypes  # need 'pip install comtypes'
    ^^^^^^^^^^^^^^^
  File "D:\script\longEnglish\pyJianYingDraft\venv\Lib\site-packages\comtypes\__init__.py", line 375
    except COMError, err:
           ^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized
最后卸载了3.13 安装了3.10 完美运行起来了

**Comment by zzZ-F** [comment]
comtypes  这个包的问题 跟3.13好像不行，然后我pip install comtypes==1.1.9
这个版本，后面报错还是提示说是这个报错 SyntaxError: multiple exception types must be parenthesized 是因为 comtypes 包使用了旧版 Python 的异常捕获语法，而这个语法在新版的 Python 中已经不再支持。 然后我卸载了3.13 重新装了3.10就完美运行了

**Comment by GuanYixuan** [comment]
> comtypes 这个包的问题 跟3.13好像不行，然后我pip install comtypes==1.1.9 这个版本，后面报错还是提示说是这个报错 SyntaxError: multiple exception types must be parenthesized 是因为 comtypes 包使用了旧版 Python 的异常捕获语法，而这个语法在新版的 Python 中已经不再支持。 然后我卸载了3.13 重新装了3.10就完美运行了

感谢提供线索，此前确实还不知道这里也会出问题

**Comment by javenfang** [comment]
在 Mac 环境下，这里必须出错的，看起来，批量导出功能就是只能在 Windows 下才能用的。 
@GuanYixuan  希望 Readme 里能够明确标出来。


`Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/comtypes/__init__.py", line 5, in <module>
    from _ctypes import COMError  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'COMError' from '_ctypes' (/opt/anaconda3/lib/python3.12/lib-dynload/_ctypes.cpython-312-darwin.so)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/javenfang/Coding/pyJianYingDraft/test.py", line 2, in <module>
    from pyJianYingDraft import (
  File "/Users/javenfang/Coding/pyJianYingDraft/pyJianYingDraft/__init__.py", line 21, in <module>
    from .jianying_controller import Jianying_controller
  File "/Users/javenfang/Coding/pyJianYingDraft/pyJianYingDraft/jianying_controller.py", line 5, in <module>
    import uiautomation as uia
  File "/opt/anaconda3/lib/python3.12/site-packages/uiautomation/__init__.py", line 4, in <module>
    from .uiautomation import *
  File "/opt/anaconda3/lib/python3.12/site-packages/uiautomation/uiautomation.py", line 24, in <module>
    import comtypes  # need 'pip install comtypes'
    ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/comtypes/__init__.py", line 15, in <module>
    raise ImportError(msg) from e
ImportError: COM technology not available (maybe it's the wrong platform).
Note that COM is only supported on Windows.`

**Comment by GuanYixuan** [comment]
是的，因为`uiautomation`这套东西本来就是微软做的，所以在Mac上肯定没法直接跑，不过确实还是标出来比较好

**Comment by wangzhione** [comment]
comtypes >= 1.4.8 以上版本 , 已经支持 python3.13 了. 

不过遇到另外问题, 在 8.6 跑不了
