### ISSUE TITLE
能否支持mac？

### ISSUE THREAD

**Issue by chaiwenjun000** [GuanYixuan/pyJianYingDraft#15]
rt

**Comment by GuanYixuan** [comment]
由于缺少相应的设备，预计在短时间内不会支持Mac（至少自动导出功能是如此）。

不过若有兴趣可以测试一下其它草稿相关功能是否自动兼容Mac（即，两个平台上的剪映草稿格式是不是一致的）

**Comment by chaiwenjun000** [comment]
感谢回复。之前尝试了一下，发现一些包是windows的，没有跑起来。改天还是找个pc电脑试着跑一下。

**Comment by javenfang** [comment]
是的，我跑出来确认，当前是不支持 Mac 的。

> ImportError: COM technology not available (maybe it's the wrong platform).
> Note that COM is only supported on Windows.
> 

`Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/comtypes/__init__.py", line 5, in <module>
    from _ctypes import COMError  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'COMError' from '_ctypes' (/opt/anaconda3/lib/python3.12/lib-dynload/_ctypes.cpython-312-darwin.so)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/javenfang/Coding/pyJianYingDraft/test.py", line 2, in <module>
    from pyJianYingDraft import (
  File "/Users/javenfang/Coding/pyJianYingDraft/pyJianYingDraft/__init__.py", line 21, in <module>
    from .jianying_controller import Jianying_controller
  File "/Users/javenfang/Coding/pyJianYingDraft/pyJianYingDraft/jianying_controller.py", line 5, in <module>
    import uiautomation as uia
  File "/opt/anaconda3/lib/python3.12/site-packages/uiautomation/__init__.py", line 4, in <module>
    from .uiautomation import *
  File "/opt/anaconda3/lib/python3.12/site-packages/uiautomation/uiautomation.py", line 24, in <module>
    import comtypes  # need 'pip install comtypes'
    ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/comtypes/__init__.py", line 15, in <module>
    raise ImportError(msg) from e

ImportError: COM technology not available (maybe it's the wrong platform).
Note that COM is only supported on Windows.

`

**Comment by GuanYixuan** [comment]
没错，`uiautomation`是不支持Mac的（已在README中标出），不过可以继续看看剪映草稿的格式是否通用

**Comment by datougua** [comment]
我试着用mac跑，发现进入草稿后，文件都是丢失状态，还要手动链接，不知道要修改哪里

**Comment by lqloveball** [comment]
真机测试 Mac ，3.11 版本，屏蔽掉`uiautomation ` 
只有这个需要 window，同时如果只是操作草稿，不需要控制批量输出
也就是不使用jianying_controller.py 部分代码，在 Mac 下正常使用没有兼容问题，正常使用。

**Comment by GuanYixuan** [comment]
> 真机测试 Mac ，3.11 版本，屏蔽掉`uiautomation ` 只有这个需要 window，同时如果只是操作草稿，不需要控制批量输出 也就是不使用jianying_controller.py 部分代码，在 Mac 下正常使用没有兼容问题，正常使用。

所以是直接屏蔽掉`uiautomation`就能用了吗？我之前的理解是它生成的草稿还不能直接用Mac版的剪映打开，因为可能有一些跟平台相关的字段不对

**Comment by f1748x** [comment]
> 有大佬支持MAC版本吗

我正在研发mac版本的，遇到了一个问题，你们是怎么监控剪映是否完成了本次倒入的？

**Comment by MarkHimon** [comment]
剪影天天更新，随时 扼杀，有无官方解决方案

**Comment by Lingeng56** [comment]
请问大家模版素材都怎么收集吗？macos读取的似乎不是draft_content.json，反而是生成了一个template.json文件，好像还是混合加密过的
