### ISSUE TITLE
添加时间的问题

### ISSUE THREAD

**Issue by pretty2015** [GuanYixuan/pyJianYingDraft#4]
感谢作者的库，代码片段如下：
```python
for j, (audio_file, audio_duration) in enumerate(zip(audio_files, audio_durations)):
            audio_material = draft.Audio_material(audio_file)
            script.add_material(audio_material)
            audio_segment = draft.Audio_segment(audio_material,
                                                trange(f"{current_time}s", f"{current_time + audio_duration}s"),
                                                volume=1.0)
            script.add_segment(audio_segment)
            logging.debug(f"重新计算{audio_file}: {audio_material.duration / 1000000} 秒")
            logging.debug(f"原音频片段时长: {audio_duration} 秒")
            logging.info(f"添加音频片段 {j+1}, 开始时间: {current_time}s, 结束时间: {current_time + audio_duration}s")
            current_time += audio_duration
```
运行后报错：
```
2024-09-14 11:32:49,033 - INFO - 生成的音频总时长: 9.504 秒
2024-09-14 11:32:49,051 - DEBUG - 重新计算temp/audio_2.mp3: 3.564 秒
2024-09-14 11:32:49,052 - DEBUG - 原音频片段时长: 3.564 秒
2024-09-14 11:32:49,052 - INFO - 添加音频片段 1, 开始时间: 0s, 结束时间: 3.564s
Traceback (most recent call last):
  File "Z:\2.programing\pyJianYingDraft\txt2jianyingdraft.py", line 187, in <module>
    main()
  File "Z:\2.programing\pyJianYingDraft\txt2jianyingdraft.py", line 135, in main
    audio_segment = draft.Audio_segment(audio_material,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\2.programing\pyJianYingDraft\pyJianYingDraft\audio_segment.py", line 141, in __init__
    raise ValueError(f"Source timerange {source_timerange} exceeds material duration {material.duration}")
ValueError: Source timerange [start=0, end=6876000] exceeds material duration 3312000
```
另外想请教一下，如何添加多个音轨（背景音和口播两个）及添加素材到指定同类的轨道呢。 
感谢！

**Comment by GuanYixuan** [comment]
报的错是说从一个长度为3312000的素材里截取长度为6876000的片段，素材不够长。可能是因为应该用`audio_duration`而不是`current_time + audio_duration`作为片段时长？（注意`trange`的第二个参数是时长而不是结束时间）

关于多个轨道，`Script_file.add_track`和`Script_file.add_segment`方法都有第二个参数可以指定轨道的名称，例如可以考虑：
```
# 创建两个音频轨道
script.add_track(draft.Track_type.audio, "bgm")
script.add_track(draft.Track_type.audio, "voice")

# 分别向两个轨道中添加片段
script.add_segment(bgm_segment, "bgm")
script.add_segment(voice_segment, "voice")
```

目前readme中确实没有明确提到以上内容，所以我也计划将相应的说明补充进去，感谢您提出的问题

**Comment by pretty2015** [comment]
感谢。 确实，项目库代码没有问题，是我使用问题。按你的方法自定义轨道名也成功。
